<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProfilePromptUpdateRequest;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;

class ResponseManagementController extends Controller
{
    public function index(Request $request)
    {
        $user = $request->user();

        return view('response-management.index', [
            'user' => $user
        ]);
    }

    public function toggleAutoGeneration(Request $request): RedirectResponse
    {
        $user = $request->user();
        $autoGenerated = $user->auto_generated;

        $user->update([
            'auto_generated' => !$autoGenerated
        ]);

        return Redirect::route('response-management.index');
    }

    public function toggleAutoAnswered(Request $request): RedirectResponse
    {
        $user = $request->user();
        $autoAnswered = $user->auto_answered;

        $user->update([
            'auto_answered' => !$autoAnswered
        ]);

        return Redirect::route('response-management.index');
    }

    public function updatePrompt(ProfilePromptUpdateRequest $request): RedirectResponse
    {

        $request->user()->fill($request->validated());

        if ($request->user()->isDirty('email')) {
            $request->user()->email_verified_at = null;
        }

        $request->user()->save();

        return Redirect::route('response-management.index')->with('status', 'prompt-updated');
    }

}
